name: build

on:
  push:
    tags:
    - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get tag name
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            shapirus/kustomize-benchmark-suite:latest
            shapirus/kustomize-benchmark-suite:${{ steps.get_tag.outputs.TAG }}
          push: true
